### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by zielony12** [kraxarn/spotify-qt#116] opened 2021-08-23 14:30 UTC
### System information
OS: FreeBSD 13.0-RELEASE

### Detailed information
Cannot authenticate

### What happens?
At welcome message i have entered my new app id and token but it wont log in me. It opens new tab in my web browser and i have a message: "INVALID_CLIENT: Invalid redirect URI"

### What should happen?
It should log me in

**Comment by kraxarn** [comment] 2021-08-23 18:40
Duplicate of #3?
(enter the specified URL from the app in “Redirect URIs” and not “Website”)

**Closed** 2021-08-31 14:09 UTC
