### ISSUE TITLE
Allow more/custom parameters for librespot

### ISSUE THREAD

**Issue by JustMyGithub** [kraxarn/spotify-qt#229] opened 2023-09-08 12:23 UTC
Librespot has quite a bunch of useful parameters, like normalisation that are not supported by spotify-qt yet:

`target/release/librespot -n "Librespot" -b 320 -c ./cache --enable-volume-normalisation --initial-volume 75 --device-type avr`

so it would be nice to have just a text field in spotify-qt to add custom parameters (so you do not need to implement all the parameters to GUI one by one)

**Comment by kraxarn** [comment] 2023-09-23 13:55
Closing as a duplicate of #223.

**Closed by kraxarn** 2023-09-23 13:55 UTC
