### ISSUE TITLE
No refresh token

### ISSUE THREAD

**Issue by wnm210** [kraxarn/spotify-qt#185] opened 2022-09-04 17:33 UTC
### System information
![image](https://user-images.githubusercontent.com/49320100/188325944-a80c3000-f0cc-4532-81d8-7b964ff48e17.png)

### Detailed information
Web server returns `success, you can now return to spotify-qt`
but app says `Unexpected response: No refresh token`.
![image](https://user-images.githubusercontent.com/49320100/188326136-d7b346ae-a10d-4c88-bc19-4db783ff27ff.png)

### Logs
```
wnm210@nove-org:~/Desktop$ ./spotify-qt-v3.9.AppImage
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
[07:31:52 PM] [err ] [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```

**Comment by kraxarn** [comment] 2022-09-04 19:12
Closing as a duplicate of #182, but good to know it's not specific to Fedora.

**Closed by kraxarn** 2022-09-04 19:12 UTC
