### ISSUE TITLE
spotify-qt crashes when no playlists are found

### ISSUE THREAD

**Issue by mikedebian** [kraxarn/spotify-qt#17] opened 2020-07-04 15:05 UTC
Was told to post the issue here from the haiku forums.

Here is the relevant pastebin

https://pastebin.com/2BNDZS2J

Segmentation fault.

I don't know if this is something you're willing to do anything about, but posting it anyway.
Help appreciated :)

https://discuss.haiku-os.org/t/tip-how-to-get-spotify-qt-running/9746/11

**Comment by Begasus** [comment] 2020-07-04 15:28
@mikedebian was this on 64bit? I have the same issue on 32bit Haiku

**Comment by mikedebian** [comment] 2020-07-04 15:30
@Begasus This is x86_64 (64-bit).

Interesting to know that it's not because of x86_64, thanks! :)

**Comment by kraxarn** [comment] 2020-07-04 17:19
I'm not too familiar with Haiku, but someone did get it working without modification in #16. I could also set up an environment to check for myself and see if I can reproduce it.

**Comment by kraxarn** [comment] 2020-07-05 11:01
I'm not able to reproduce the issue, as it seems to work just fine in my virtual environment with an updated version of Haiku. You can try running cmake with `cmake -DCMAKE_BUILD_TYPE=Debug ..` and then run the application through `gdb` to see if you get any helpful output from there.

**Comment by Begasus** [comment] 2020-07-05 15:19
I don't have a premium account at spotify, not sure if others that don't have it also suffers from this, but will check a build with Debug enabled

**Comment by mikedebian** [comment] 2020-07-06 16:08
I have premium, no freemium. Read from others that it does not matter.

**Comment by kraxarn** [comment] 2020-07-08 20:25
Possibly fixed in d3542a4c4a5185331e6638a0ee0633c016a67788, as one of the possible causes was that no playlists were found to load. Please either wait for the next release or compile from source to see if the issue is resolved.

**Comment by Begasus** [comment] 2020-07-09 06:01
Seems to be fixed!

![Spotify-Qt](https://user-images.githubusercontent.com/16057090/87002663-5e655b00-c1ba-11ea-83f5-64a5aaafa097.png)

**Comment by Begasus** [comment] 2020-07-09 08:02
Merged a source checkout at haikuports for this at https://github.com/haikuports/haikuports/pull/5179

**Comment by mikedebian** [comment] 2020-07-09 08:11
Fixed in newest revision.

**Comment by kraxarn** [comment] 2020-07-09 08:13
Great. Then it should probably just handle it a bit better before closing the issue.

**Comment by Begasus** [comment] 2020-07-09 08:17
As mentioned in the forum by @mikedebian it probably needs spotifyd to be able to load the playlists?

**Comment by kraxarn** [comment] 2020-07-09 08:24
spotifyd is only used for music playback, playlist are fetched directly from the Spotify API. The only integration with spotifyd is that it can be configured from within the app, but it's not required. If you have playlists and they aren't showing in the application, that's a separate issue.

**Comment by Begasus** [comment] 2020-07-09 08:30
Ok, then for Haiku it seems to be ok and a seperate issue for not loading the playlist should be created, thanks for clarification!

**Closed** 2020-07-09 09:43 UTC
