### ISSUE TITLE
nightly build hangs when starting librespot or spotifyd

### ISSUE THREAD

**Issue by ssmccoy** [kraxarn/spotify-qt#260] opened 2024-08-28 18:16 UTC
### System information
Nightly Build

```
scott@fury:~/Desktop> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
scott@fury:~/Desktop> uname -a
Linux fury 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
scott@fury:~/Desktop> spotifyd --version
spotifyd 0.3.5
scott@fury:~/Desktop> librespot --version
librespot 0.5.0-dev 2ea7436 (Built on 2024-08-28, Build ID: f6lWwoLL, Profile: release)
```

### Detailed information
```
scott@fury:~/Desktop> ./spotify-qt-v3.11-240825.AppImage
```

Fresh install. Configure API key as described.
Set path for either spotifyd or librespot. Click "Start Client"

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Signal: 11, faulty address at 0x10206 from 0x7ffea6d33e20
#0  /tmp/.mount_spotif70uPnq/AppRun.wrapped(+0x176000) [0x5da5b3a8f000]
#1  [0x7ffea6d33e20]
#2  /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Core.so.6(_ZN7QObject11deleteLaterEv+0x15) [0x7adef17b2035]
#3  /tmp/.mount_spotif70uPnq/AppRun.wrapped(+0xac448) [0x5da5b39c5448]
#4  /tmp/.mount_spotif70uPnq/AppRun.wrapped(+0xe5629) [0x5da5b39fe629]
#5  /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Core.so.6(+0x1c17ca) [0x7adef17c17ca]
#6  /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(_ZN15QAbstractButton7clickedEb+0x32) [0x7adef089f9d2]
#7  /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(+0x29fc1a) [0x7adef089fc1a]
#8  /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(+0x2a1700) [0x7adef08a1700]
#9  /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(_ZN15QAbstractButton17mouseReleaseEventEP11QMouseEvent+0xee) [0x7adef08a197e]
#10 /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(_ZN7QWidget5eventEP6QEvent+0x19e) [0x7adef07dbaee]
#11 /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x82) [0x7adef07844f2]
#12 /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x430) [0x7adef078ce10]
#13 /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Core.so.6(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x14a) [0x7adef176318a]
#14 /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb+0x1e0) [0x7adef078c160]
#15 /tmp/.mount_spotif70uPnq/usr/bin/../lib/libQt6Widgets.so.6(+0x1eda81) [0x7adef07eda81]
```

### What happens?
Application freezes after above stacktrace.

### What should happen?
I assume I should be able to play music.

**Comment by kraxarn** [comment] 2024-09-12 19:19
Closing as a duplicate of #251

**Closed by kraxarn** 2024-09-12 19:19 UTC
