### ISSUE TITLE
Podcasts?

### ISSUE THREAD

**Issue by Reckermatouvc** [kraxarn/spotify-qt#135] opened 2021-11-09 11:32 UTC
Hello! First of all I wanted to thank you for all the work in this amazing app.

I use your app daily but I noticed there's no podcast option.

Am I missing the feature or is it unavailable? Is there a way to implement it or it's impossible because of the Web API? Thanks in advance.

**Comment by kraxarn** [comment] 2021-11-09 19:04
Thank you :relaxed:
Seems to be a duplicate of #110. It's implemented, and to be included in the next release, but if you want to try it now, you can compile the application from the master branch yourself, or download the latest binary from GitHub Actions.

**Closed by kraxarn** 2021-11-09 19:04 UTC
