### ISSUE TITLE
Failed to start playback: Player command failed: No active device found

### ISSUE THREAD

**Issue by LuckoB** [kraxarn/spotify-qt#55] opened 2021-02-07 15:38 UTC
### System information
I am using spotify-qt V3.3 on a linux Ubuntu 20.04.2 LTS. I installed it using `sudo snap install spotify-qt`.

### Detailed information
I never used it, I just tried today, but it wouldn't work.

### What happens?
I started the app and tried to play some music, but the error message appeared on the bottom of the window: "Failed to start playback: Player command failed: No active device found"

### What should happen?
I expected that some music would play. I tried looking in my sound settings, but all was normal. I had speakers in my screen and in my connected laptop (DELL XPS-13-9360) and I also tried to connect headphones, but nothing worked. When I go in the menu/Device in the app, there is no device available. It's only write "no devices found".

Thanks in advance

**Comment by kraxarn** [comment] 2021-02-07 18:40
Duplicate of #26, see also my comment there for more info.

Currently, the app can't play any music by itself, although, it's something that's planned. I would recommend installing `spotifyd` from snap as well, and then configure `spotify-qt` to use it, for example setting the path to `/snap/spotifyd/current/bin/spotifyd` inside the app. Let me know if you have any issues :relaxed:

**Comment by AntonioManceraGamez** [comment] 2021-02-15 09:16
Hello! I'm triying to do that but when I puth the path (which I supose is the correct one becouse it's there if I search it in the file explorer) throw me an error: Failed to apply setting "spotifyd path". Check your setting and try again.

**Comment by pghpete** [comment] 2021-02-25 00:46
raspotify is also another option, to make your raspberry pi a spotify "target" to play to.

**Comment by kraxarn** [comment] 2023-02-11 11:29
Closing due to inactivity. Feel free to re-open if you encounter any other issues.

**Closed by kraxarn** 2023-02-11 11:29 UTC

**Comment by RokeJulianLockhart** [comment] 2025-02-16 19:55
> https://github.com/kraxarn/spotify-qt/issues/55#issuecomment-1426704640

@kraxarn, I've just reproduced this in `spotify-qt-3.12-1.fc41.x86_64`:

![Image](https://github.com/user-attachments/assets/23e5d63a-e99f-4601-8ec0-2639461a2273)

If unaware, it appears to relate to https://github.com/brianstrauch/spotify-cli/issues/38#issue-941879809.

#### Environment

1.	#### OS & DE

	1.	~~~sh
		#!/usr/bin/env sh
		kinfo
		~~~

	1.	<blockquote>

		~~~YAML
		Operating System: Fedora Linux 41
		KDE Plasma Version: 6.3.0
		KDE Frameworks Version: 6.11.0
		Qt Version: 6.8.2
		Kernel Version: 6.12.13-200.fc41.x86_64 (64-bit)
		Graphics Platform: Wayland
		Processors: 16 × AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
		Memory: 30.6 GiB of RAM
		Graphics Processor: AMD Radeon 780M
		~~~

		</blockquote>

1.	#### Application

	1.	~~~sh
		#!/usr/bin/env sh
		dnf info --refresh spotify-qt
		~~~

	1.	<blockquote>

		~~~YAML
		Updating and loading repositories:
		 RPM Fusion for Fedora 41 - Free - Updates Debug              100% |  55.8 KiB/s |   8.0 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Nonfree tainted - Debug           100% |  23.0 KiB/s |   9.1 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Free tainted - Debug              100% |  51.7 KiB/s |   8.5 KiB |  00m00s
		 Fedora 41 - x86_64 - Updates                                 100% |  62.4 KiB/s |  24.7 KiB |  00m00s
		 Fedora 41 openh264 (From Cisco) - x86_64                     100% |   2.9 KiB/s | 989.0   B |  00m00s
		 RPM Fusion for Fedora 41 - Free tainted                      100% |  52.3 KiB/s |   8.2 KiB |  00m00s
		 Fedora 41 openh264 (From Cisco) - x86_64 - Debug             100% |   2.4 KiB/s | 997.0   B |  00m00s
		 Fedora 41 - x86_64 - Debug                                   100% |  45.1 KiB/s |  20.6 KiB |  00m00s
		 google-chrome-canary                                         100% |  17.9 KiB/s |   1.3 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Free                              100% |  57.3 KiB/s |   8.9 KiB |  00m00s
		 Fedora 41 - x86_64 - Updates - Debug                         100% |  28.4 KiB/s |  19.9 KiB |  00m01s
		 RPM Fusion for Fedora 41 - Nonfree tainted                   100% |  22.2 KiB/s |   8.8 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Nonfree - Updates Debug           100% |  21.4 KiB/s |   8.6 KiB |  00m00s
		 Copr repo for Koi owned by birkch                            100% |   9.0 KiB/s |   1.5 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Free - Debug                      100% |  56.0 KiB/s |   9.0 KiB |  00m00s
		 warpdotdev                                                   100% |   9.7 KiB/s |   1.5 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Free - Updates                    100% |  23.6 KiB/s |   7.7 KiB |  00m00s
		 Copr repo for spotify-qt owned by kraxarn                    100% |  10.6 KiB/s |   1.5 KiB |  00m00s
		 Fedora 41 - x86_64                                           100% |  67.7 KiB/s |  26.8 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Nonfree - Updates                 100% |  21.0 KiB/s |   8.3 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Nonfree                           100% |  23.3 KiB/s |   9.5 KiB |  00m00s
		 RPM Fusion for Fedora 41 - Nonfree - Debug                   100% |  24.8 KiB/s |   9.7 KiB |  00m00s
		 Visual Studio Code                                           100% |  13.5 KiB/s |   1.5 KiB |  00m00s
		Repositories loaded.
		Installed packages
		Name            : spotify-qt
		Epoch           : 0
		Version         : 3.12
		Release         : 1.fc41
		Architecture    : x86_64
		Installed size  : 2.2 MiB
		Source          : spotify-qt-3.12-1.fc41.src.rpm
		From repository : copr:copr.fedorainfracloud.org:kraxarn:spotify-qt
		Summary         : Lightweight Spotify client using Qt
		URL             : https://github.com/kraxarn/spotify-qt
		License         : GPLv3
		Description     : An unofficial Spotify client using Qt as a simpler, lighter alternative to the offic
		                : ial client.
		Vendor          : Fedora Copr - user kraxarn

		Available packages
		Name           : spotify-qt
		Epoch          : 0
		Version        : 3.12
		Release        : 1.fc41
		Architecture   : src
		Download size  : 1.8 MiB
		Installed size : 1.8 MiB
		Repository     : copr:copr.fedorainfracloud.org:kraxarn:spotify-qt
		Summary        : Lightweight Spotify client using Qt
		URL            : https://github.com/kraxarn/spotify-qt
		License        : GPLv3
		Description    : An unofficial Spotify client using Qt as a simpler, lighter alternative to the offici
		               : al client.
		Vendor         : Fedora Copr - user kraxarn
		~~~

		</blockquote>
