### ISSUE TITLE
Hardware media controls don't seem to work, whether inside or outside the window

### ISSUE THREAD

**Issue by a-singer** [kraxarn/spotify-qt#119] opened 2021-08-30 21:26 UTC
Hi,

	My keyboard, like most, has multimedia controls as special keys (rewind, play/pause, FF, Stop). These work with many players, but don't seem to do anything in Spotify-QT. Are they supposed to, if I may ask? If not, would it be possible for these buttons to work? As it is, and this may well be my machine since I have only tried it on one, nothing at all happens when I hit them.
Thanks for looking into this,

**Comment by kraxarn** [comment] 2021-08-31 08:10
It's currently only supported under Linux, as that's my preferred development platform, and Windows support is simply something I'll probably not implement myself, but if someone else wants to contribute, they are very welcome to.

**Comment by marcoshsbosco** [comment] 2021-11-23 17:44
Sorry for bumping suck an old issue (although I guess it hasn't been closed anyway), but, on Arch Linux with Plasma 5.23, I can't get the hardware media keys to work either. Any clue on why that may be?

**Comment by kraxarn** [comment] 2021-11-23 21:24
Closing this as it's really a duplicate of #4, but it's a known issue that I'm working on trying to improve. As a workaround, you can for example use playerctl.

**Closed by kraxarn** 2021-11-23 21:24 UTC

**Comment by sunjerry019** [comment] 2024-05-07 08:29
Hi there, sorry to necrobump this, but I am currently on:
```
plamsa 5.27.6
spotify-qt v3.11 (commit 83bfc5df) / AppImage
```
and I am having this exact same issue with the hardware media buttons. Additionally, when hovering over the icon of `spotify-qt` in the taskbar, only the playback volume controls are displayed and not media controls. Do you have an idea on where the problem could lie? Thanks!

**Comment by kraxarn** [comment] 2024-07-04 15:28
If you are on Linux and it still doesn't work, please open a new issue with more info and logs, thanks!

**Comment by sunjerry019** [comment] 2024-07-04 16:54
> If you are on Linux and it still doesn't work, please open a new issue with more info and logs, thanks!

Thanks for answering this! Have there been new commits that are relevant, or just in reference to `v3.11`? 
What kind of logs and info would be useful?

**Comment by kraxarn** [comment] 2024-07-05 09:58
Not much about this has changed since v3.9, so if there are issues in version v3.9 or later, something else I'm not aware of could be wrong.

Logs from "Settings > Logs > Application logs" and info from "Settings > Troubleshooting > System" could be useful, thanks!
