### ISSUE TITLE
Inverted playlist plays wrong song if there are unavailable songs on it

### ISSUE THREAD

**Issue by eltsu7** [kraxarn/spotify-qt#226] opened 2023-08-03 06:57 UTC
### System information

Windows11
spotify-qt v3.10
Commit 4cc793e

### Detailed information

When clicking on playlist with **inverted** track number order with that playlist having unavailable songs, the song played will be offset by one for every unavailable song under it. Examples from a single playlist below:

This is the bottom of the playlist, I clicked on track 7 and it started playing correctly. No issues here. You can see that track 13 is the first unavailable track.
![image](https://github.com/kraxarn/spotify-qt/assets/23433034/3ca31d95-b69e-4ae8-acf2-fcd10aa197d6)

Then I clicked on track 18, it plays track 19 instead:
![image](https://github.com/kraxarn/spotify-qt/assets/23433034/63ffb1c4-ff22-47b3-a7dd-fb46dc545ddb)

Above the second unavailable track(104) the offset it 2: I clicked on track 105 and it played 107:
![image](https://github.com/kraxarn/spotify-qt/assets/23433034/0c5fcd4a-7d24-4c7e-832f-fa4bea27745e)

If I click on the 2 topmost tracks it just stops playing.

Here is the playlist: https://open.spotify.com/playlist/04uEKBzsuuCmHYm96e6Z3F

### What happens?

Wrong song played.

### What should happen?

Right song played.

**Comment by kraxarn** [comment] 2023-09-23 13:41
Closing as a duplicate of #209. Seems like the same issue, but nice to have another playlist to test with.

**Closed by kraxarn** 2023-09-23 13:41 UTC

**Comment by treeshateorcs** [comment] 2024-05-19 00:39
Is it intentional that songs in inverted playlists play in the default order? (bottom to top)

**Comment by kraxarn** [comment] 2024-07-04 15:31
Yes, afaik, there's no way to tell the Spotify API which order you want tracks played in, so they will always play in the numbered order, no matter how they are sorted.
