### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by N-35** [kraxarn/spotify-qt#181] opened 2022-07-21 17:18 UTC
Im using bspwm on Arch with the Linux kernel.

I've reinstalled the spotify-qt AUR package after using spotify-tui for a while, now whenever I try to launch it I get the Error Message

Unexpected response:
Refresh token revoked

This persists across reinstalls and/or reboots

**Comment by kraxarn** [comment] 2022-07-29 19:05
Most likely a duplicate of #64. I have plans to handle this much better, but as a temporary fix, you can try starting spotify-qt with `--reset-credentials` to reauthenticate.

**Comment by kraxarn** [comment] 2023-02-11 11:49
Closing this as this issue is now resolved.

**Closed by kraxarn** 2023-02-11 11:49 UTC
