### ISSUE TITLE
Cannot output sound locally, just control other Spotify Devices

### ISSUE THREAD

**Issue by smnbldwn** [kraxarn/spotify-qt#170] opened 2022-05-11 14:36 UTC
OS: FreeBSD 13.0-RELEASE-p11 i386 
Resolution: 1024x600 
DE: Xfce4 4.16 
WM: Xfwm4 
CPU: Intel Atom N270 (2) @ 1.600GHz 
GPU: Mobile 945GSE Express Integrated Graphi 
Memory: 480MiB / 2012MiB 

### Detailed information
When I open Spotfy-qt it logs in successfully to my spotify account and loads my playlists etc but the only available devices are other devices I have open and running Spotify. It can't playback on the local device. 

When I open Spotify -QT it opens fine, I have put the username and password in the settings and it successfully logs in and displays the playlists etc. It used to be that I could only start and stop playback that was already running on another device but now I can navigate and choose songs and it all plays on the other device. The "device" option only allows me to choose other devices.

I should be able to choose the local device and playback through the internal sound card.

**Comment by kraxarn** [comment] 2022-06-06 15:18
spotify-qt currently doesn't provide any playback functionality by itself, but can make use of for example librespot or spotifyd for playback, which can be configured from within the app. Closing as duplicate of #26, but I plan on clearing this up a bit, due to the amount of similar issues.

**Closed by kraxarn** 2022-06-06 15:18 UTC
