### ISSUE TITLE
Inconsistent spotifyd connection

### ISSUE THREAD

**Issue by emmatebibyte** [kraxarn/spotify-qt#153] opened 2022-03-01 08:39 UTC
### System information

Artix Linux (openrc) with KDE Plasma 5.24.2
### Detailed information

spotify-qt can connect to spotifyd for a short amount of time, but then loses connection to spotifyd.
### What happens?

Run the app and listen to music. I will work for a bit, then stop because spotifyd is no longer connected.
### What should happen?

Music plays normally.

**Comment by johnyenter-briars** [comment] 2022-03-02 16:21
Are you using a VPN at all? This will happen to me when connecting through NordVPN. When Nord is on, spotifyd will work for like two minutes, but then will stop playing. Note: `systemctl status --user spotifyd` doesn't show any relevant debug info. 

AFAIK, its an issue with Spotifyd, not with SpotifyQt.

**Comment by emmatebibyte** [comment] 2022-03-02 17:05
@johnyenter-briars I have tor on, maybe that's it, but I'm not usually connected through it when I'm running spotifyd. Openrc isn't giving me any details either, but that could be because it's running as a user process being started by spotify-qt and not rc-service.

**Comment by johnyenter-briars** [comment] 2022-03-02 17:31
@emmatebibyte  - one thing you might try to isolate the issue is: connecting to spotifyd via a different spotify client? If something like [spotify-tuiI](https://github.com/Rigellute/spotify-tui) is still able to control spotifyd then it's a confirmed bug in spotify-qt.

**Comment by johnyenter-briars** [comment] 2022-03-02 17:34
@emmatebibyte  - one thing you might try to isolate the issue is: connecting to spotifyd via a different spotify client? If something like [spotify-tuiI](https://github.com/Rigellute/spotify-tui) is still able to control spotifyd then it's a confirmed bug in spotify-qt.

**Comment by kraxarn** [comment] 2022-03-05 09:51
spotifyd and librespot can also be started directly from CLI, which what spotify-qt does anyway. If starting spotify-qt with the --dev flag, the log will show the exact command it executes. If it still doesn't work outside the application, it's probably an issue with spotifyd, and not an issue with psotify-qt itself.

**Comment by herrhotzenplotz** [comment] 2022-04-12 08:43
Quick note: spotifyd has proven itself to me to be quite buggy and
susceptible to network connectivity hiccups. I have seen it print
errors to the syslog /var/log/messages (that is on FreeBSD), panic
randomly and crash when reloading firewall rules.

To debug this you may wanna run it by hand:

```console
spotifyd --no-daemon --verbose
```

This should give you noisy output without detaching from the terminal
- hopefully providing you with some helpful information about the
problem.

**Comment by emmatebibyte** [comment] 2022-04-18 00:32
@herrhotzenplotz thanks for this—I was able to pin down a few problems this way, but also `spotifyd` refuses to connect to spotify clients unless I specify the `--no-daemon` flag.

**Comment by kraxarn** [comment] 2022-06-06 08:31
Closing as it's more of an issue with spotifyd, and probably not related to spotify-qt itself.

**Closed by kraxarn** 2022-06-06 08:31 UTC
