### ISSUE TITLE
Support collaborative playlists

### ISSUE THREAD

**Issue by jkhsjdhjs** [kraxarn/spotify-qt#160] opened 2022-03-25 22:15 UTC
It would be cool if spotify-qt supported collaborative playlists. Currently spotify-qt only supports playing songs from collaborative playlists, but it's not possible to create or modify collaborative playlists (i.e. add/delete songs).

**Comment by herrhotzenplotz** [comment] 2022-03-27 08:35
To my best knowledge, you can mark playlists as collaborative through the edit option of the playlist context menu (right click the playlist name on the left column).
You can create collaborative playlists too by first creating a new playlist and then marking it as collaborative the same way.

**Comment by jkhsjdhjs** [comment] 2022-03-27 13:25
Mhm yes, that seems to be possible, I didn't know that, thanks! However, it's not possible to modify collaborative playlists you don't own.

**Comment by herrhotzenplotz** [comment] 2022-03-27 15:45
Regarding modifying collaborative playlists:

I have done some research and it looks like this won't be possible to
implement easily. Currently, the Spotify Web API does not have a
documented endpoint for adding tracks to collaborative
playlists. Unless the folks at Spotify bother implementing this
feature (or documenting it for that matter, as it works in the
official electron app), the only solution would be reversing it. I
unfortunately don't have the time and resources for that.

**Comment by jkhsjdhjs** [comment] 2022-03-27 17:16
Ah, I see. Thanks for the research! Adding songs to other collaborative playlists indeed doesn't work via the web client.
Regarding the API, it seems someone else already requested that: https://community.spotify.com/t5/Your-Library/API-Playlists-Allow-users-to-add-tracks-to-collaborative/td-p/5334108
But it seems like the support ignored the actual request to fix the API endpoint and assumed the request to be a duplicate of some already existing requests.

Anyways, I'll leave this issue open as a feature request, maybe the spotify API will support this at some point.

**Comment by kraxarn** [comment] 2022-05-15 17:57
I just kind of assumed it would work the same as with playlists you own, but I guess I never tried it. Just tried it now, and I just get an error message saying I can't add or remove tracks from playlists I don't own. I've now removed the add and remove options, and if the feature ever becomes available in the Web API, please reopen the issue. Doesn't really make sense to keep the issue open, as it's not a bug with spotify-qt itself.

**Closed by kraxarn** 2022-05-15 17:57 UTC
