### ISSUE TITLE
High CPU Usage for no reason on KDE+Ubuntu

### ISSUE THREAD

**Issue by J-Cake** [kraxarn/spotify-qt#44] opened 2020-12-26 12:12 UTC
### System information
|||
|---|---|
|AB|x86_64-little_endian-lp64|
|App version|v3.2-dev (59fcf9b)|
|Current desktop|KDE|
|Device|Spotifyd@JCake (Speaker)|
|Kernel|linux 5.4.0-58-generic|
|Product|Ubuntu 20.04.1 LTS|
|Qt version|5.9.5|

### Detailed information
The System monitor (KSysGuard) shows the app is idling at 13%CPU Usage after being open when the device wakes from sleep. I don't believe this has anything to do with the issue, however, notably, the app was running for extended periods of time prior to CPU usage spiking

### What happens?
The App should stay open for an extended period of time and if possible be open when the device wakes from sleep. The application is playing music.

### What should happen?
The CPU usage of the application should not exceed idling usage (<1%)

**Comment by kraxarn** [comment] 2020-12-26 12:35
Maybe related to the application losing network connectivity? I know spotifyd/librespot has some issues with handling it, but it's possible the application itself also does.

**Comment by J-Cake** [comment] 2020-12-26 12:41
If this is the case, how come the application's CPU usage rises rather than the daemon?

**Comment by uninhm** [comment] 2020-12-29 23:07
In my case spotifyd is using 10% and spotify-qt 0.3%

**Comment by rajeshisnepali** [comment] 2021-01-16 14:01
For me I suppose, the issue arose after the system suspended.

 At first, it was having 100% CPU usage, and after I restarted the app, it fell to 1.3%. I'm not sure if it is related. But we need a permanent solution indeed.

**Comment by kraxarn** [comment] 2021-01-16 15:56
The only time I've been able to get high CPU usage is with slow network requests. As a lot of network requests are done while the application is running, it's possible something goes wrong when system is suspended, but it's just a guess.

**Comment by kraxarn** [comment] 2021-05-23 13:51
Can anyone confirm if this is still an issue? Networking was reworked in 3.6, which hopefully resolved this.

**Comment by J-Cake** [comment] 2021-05-24 00:51
I have recently reinstalled kubuntu, and have not noticed this issue since. I had managed to narrow the issue down to a physical fault. I had a power surge on my USB ports, which physically damaged them, causing the system to go into some sort of loop. Disabling the USB ports in the UEFI menu has resolved this.

**Comment by kraxarn** [comment] 2021-08-13 08:33
I'll close this as a duplicate of #102 for now, which is a similar issue with high CPU usage related to networking, even if it's not exactly the same. Feel free to re-open if this is still an issue after the other issue is resolved.

**Closed by kraxarn** 2021-08-13 08:33 UTC
